### ISSUE TITLE
[optimization] Gas use in `removeNFToken`

### ISSUE THREAD

**Issue by mg6maciej** [0xcert/ethereum-erc721#104]
These two lines don't need to be executed when `tokenToRemoveIndex == lastTokenIndex`.
```
    ownerToIds[_from][tokenToRemoveIndex] = lastToken;
    ownerToIds[_from][lastTokenIndex] = 0;
```
Next line covers clearing it:
```
    ownerToIds[_from].length--;
```

**Comment by mg6maciej** [comment]
Actually
```
ownerToIds[_from][lastTokenIndex] = 0;
```
is never necessary.

**Comment by MoMannn** [comment]
It was reported and fixed I believe @mg6maciej is not using the last version.

**Comment by MoMannn** [comment]
Lets continue the discussion about `tokenToRemoveIndex == lastTokenIndex` in #105.

**Comment by mg6maciej** [comment]
Oh, yeah. I even commented on removal of `ownerToIds[_from][lastTokenIndex] = 0;`, but the issue still stands. #105 is about a bug, this is about optimization. To make it clearer optimization can be applied every time a token which has the largest index for given user (assuming users have only a few tokens this may happen frequently) is transferred or burned.

Better yet, you may apply something like this: https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1031

**Comment by mg6maciej** [comment]
If you are not willing to go in the direction of 0x PR on OZ repo (removing `removeNFToken` and `addNFToken` altogether), but still brave enough, I believe (all tests pass) this change in Enumerable's `removeNFToken` will work:

```
@@ -108,11 +108,12 @@ contract NFTokenEnumerable is
     uint256 lastTokenIndex = ownerToIds[_from].length.sub(1);
     uint256 lastToken = ownerToIds[_from][lastTokenIndex];

-    ownerToIds[_from][tokenToRemoveIndex] = lastToken;
+    if (tokenToRemoveIndex != lastToken) {
+      ownerToIds[_from][tokenToRemoveIndex] = lastToken;
+      idToOwnerIndex[lastToken] = tokenToRemoveIndex;
+    }

     ownerToIds[_from].length--;
-    idToOwnerIndex[_tokenId] = 0;
-    idToOwnerIndex[lastToken] = tokenToRemoveIndex;
   }

   /**
```

As you may noticed, two updates are done conditionally, but also `idToOwnerIndex[_tokenId] = 0;` is not there anymore. This is because in `transfer`s this update is overridden by one in `addNFToken` and for `_burn` leaving this value in unspecified state won't ever cause any problems as token with this id doesn't exists and will not be read. If later token with this id is minted again, the value again is set in `addNFToken`.

**Comment by xpepermint** [comment]
@MoMannn let's test that.

**Comment by xpepermint** [comment]
Closing in favor of https://github.com/0xcert/ethereum-erc721/issues/114.
