### ISSUE TITLE
ERC 721: incomplete case for _mint

### ISSUE THREAD

**Issue by lknix** [0xcert/ethereum-erc721#11]
There is currently only internal `_mint` function, which can't be used. Either we complete it with some external function for minting or add a comment describing this is by default NOT implemented / used. We probably want to keep it since it has the code which shows how to properly mint a token using our implementation.

**Comment by lknix** [comment]
Yeah, I see the point of having internal _mint. We've added it to show how to properly mint and add tokens using our design and user should wrap this function with its own (external, with proper permission modifiers, etc.). I'd add a comment, which would say something like: "NOTE: this is a private function which should be called from user-implemented external minter. Its purpose is to show and properly initialize data structures when using this implementation". Wdyt?

**Comment by MoMannn** [comment]
Yeah I agree + the way to implement it in shown in the mock token for every specific implementation.

**Comment by MoMannn** [comment]
#16
