### ISSUE TITLE
[readability] Consider changing name of `idToIndex` and `idToOwnerIndex`

### ISSUE THREAD

**Issue by mg6maciej** [0xcert/ethereum-erc721#112]
I use to name index mappings like `idToIndexInTokens` (or `tokenIdToIndexInTokens`) and `idToIndexInOwnerToIds` (last part after `In` is the same as name of array). This makes it clear which array uses given index mapping.

**Comment by xpepermint** [comment]
Good suggestion but it's too long and less readable. We made this decision earlier.

**Comment by mg6maciej** [comment]
That's fine. I just find `idToOwner`, `idToIndex` and `idToOwnerIndex`, which are unrelated, too similar when reading the code.

**Comment by xpepermint** [comment]
Hum ... let's stay with that for now. We'll think about it.
