### ISSUE TITLE
Consider providing enumerable + metadata token

### ISSUE THREAD

**Issue by mg6maciej** [0xcert/ethereum-erc721#115]
I believe name of `NFToken` could be misleading as users might think this is the one they would want to use. I suggest renaming it to `NFTokenBasic` and adding new one `NFToken` (or `NFTokenFull`) that only extends `NFTokenEnumarable` and `NFTokenMetadata`.

**Comment by xpepermint** [comment]
Thanks, @mg6maciej for all these suggestions. We really appreciate your inputs.

Naming is always subjective, takes a lot of time to make a decision and there is never a complete consensus :). Here we follow the naming concept of the standard itself:

* `ERC721` => `NFToken`
* `ERC721`Enumerable => `NFToken`Enumerable
* `ERC721`Metadata => `NFToken`Metadata

I believe that this is a good design but I agree with you that it could be better. We tried to align our naming style with the standard. For example, we usually prepend get and set functions with `get` and `set` (e.g. `getTokenURI`) but the standard does this differently (e.g. only `tokenURI`) thus we made a decision to follow the rules that were set before us.
