### ISSUE TITLE
PrivateNet Integration

### ISSUE THREAD

**Issue by lekshmikbs123** [0xcert/ethereum-erc721#118]
Hi,
Is this code only worked in Ropsten? I just want to integrate this code to my private Net. 
I saw one command : npm run migrate -- --network Ropsten ( works in Ropsten) instead of this I used 
npm run migrate -- --network localhost:8545. But it's not connecting. How will I resolved my issue?
My network id : 54 ( That i gave to truffle.js).

**Comment by xpepermint** [comment]
Please follow the instructions in the README.
