### ISSUE TITLE
How will i fetch .json files from build folder in truffle using truffle console?

### ISSUE THREAD

**Issue by lekshmikbs123** [0xcert/ethereum-erc721#119]
Hi,
How will I call .json files from build folder  Truffle...?Truffle migration successfully completed..I worked in Privatenet...Then I tried
```

truffle console
truffle(development)> const { abi } = require('./build/contracts/MyNFT.json');
**Undefined**
```
Please help me to figured out this issue? Why it's showing undefined?

**Comment by xpepermint** [comment]
It's mentioned in the [docs](https://github.com/0xcert/ethereum-erc721#npm-1):
```
require('@0xcert/ethereum-erc721/build/contracts/MyNFT.json');
```
