### ISSUE TITLE
Should `isApprovedForAll` throw when `_owner == _operator`?

### ISSUE THREAD

**Issue by mg6maciej** [0xcert/ethereum-erc721#122]

**Comment by MoMannn** [comment]
I don't think so. Standard itself does not define it and I don't actually see real word need for it. 
Actually I am considering removing all checks here to lower GAS costs since they are unnecessary.

**Comment by mg6maciej** [comment]
I generally agree. I even tested if gas cost is lower if you [switch from single line functions returning value from mapping to public field](https://github.com/mg6maciej/erc721-implementation/commit/410f3b2665c5c3344e38ed69124057a0aba64ad3) and guess what... it is not only for deployment, but also for calls from other contracts.

I can think of one case where throwing would be useful. When other contracts call `getApproved` or `isApprovedForAll` and they have a bug in that they pass parameters that don't make sense.

I was just thinking out loud as there are differences between your implementation of `getApproved`/`isApprovedForAll`, the one from OZ and mine. You have some low-gast-cost (under 10 gas) checks there while others don't.
