### ISSUE TITLE
Not getting any values after adding NFTokenEnumerable.sol

### ISSUE THREAD

**Issue by lekshmikbs123** [0xcert/ethereum-erc721#124]
When I used this same code, I am getting the balance everything correctly. Thenn I edit the code 
for printing totalSupply()....Without adding NFTokenEnumerable, it will saying totalSupply() is not a function. BUt after the adding, I will not get anything...balanceOf() is also not working...every values getting "zero"...
```
pragma solidity ^0.4.23;

import "../tokens/NFTokenEnumerable.sol";
import "../tokens/NFTokenMetadata.sol";
import "@0xcert/ethereum-utils/contracts/ownership/Ownable.sol";

contract MyNFToken is
  NFTokenMetadata,
  Ownable,NFTokenEnumerable
{

  constructor(
    string _name,
    string _symbol
  )
    public
  {
    nftName = _name;
    nftSymbol = _symbol;
  }

  function mint(
    address _owner,
    uint256 _id
  )
    onlyOwner
    external
  {
    super._mint(_owner, _id);
  }

  function burn(
    address _owner,
    uint256 _tokenId
  )
    onlyOwner
    external
  {
    super._burn(_owner, _tokenId);
  }

}
```
Help me to solve this issue????

**Comment by MoMannn** [comment]
Only enumerable supports totalSupply(). Without enumerable extension you would need to manually code the change in NFToken contract to include the totalSupply functionality.

**Comment by lekshmikbs123** [comment]
When I added the totalSupply() function code to anywhere of  NFToken.sol and ERC721.sol, during migration it shows, the next immediate functions not executed.
```
DocstringParsingError: Documented parameter "_to" not found in the parameter list of the function.
,DocstringParsingError: Documented parameter "_tokenId" not found in the parameter list of the function.

```
If added this functions to the last of the NFToken.sol, then during running the output shows:
`TypeError: web3.eth.contract(...).at(...).totalSupply is not a function`

Please help me figure out this issue?

**Comment by MoMannn** [comment]
It is not enough to just copy the totalSupply function you need to actually make the logic around it.. I would recommend just using enumerable extension.
