### ISSUE TITLE
balanceOf is always empty

### ISSUE THREAD

**Issue by odiblocha** [0xcert/ethereum-erc721#126]
If we call this mint function in our contract from outside (Truffle console), then everything is working as expected:

    function mint( address _to, string _uri ) onlyOwner external {
        uint256 newTokenId = _getNextTokenId();
        super._mint(_to, newTokenId);
        super._setTokenUri(newTokenId, _uri);
    }

If we call our custom _createToken function from within our contract: 

    function _createToken( address _to, string _uri ) internal {
        uint256 newTokenId = _getNextTokenId();
        super._mint(_to, newTokenId);
        super._setTokenUri(newTokenId, _uri);
    }

    function someFunction (UriString) {
        _createToken(msg.sender, UriString);
    }

Then balanceOf(senderAddress) stays zero. Other functions like tokenURI or totalSupply are working as expected. Are we doing something wrong in our custom function?

**Comment by MoMannn** [comment]
I tried this part of the code:

```
function _createToken( address _to, string _uri ) internal {
    uint256 newTokenId = _getNextTokenId();
    super._mint(_to, newTokenId);
    super._setTokenUri(newTokenId, _uri);
}

function someFunction (UriString) {
    _createToken(msg.sender, UriString);
}
```

But I changed `_getNextTokenId();` to 5 because you did not provide the code for it and it works normally.. I tried with NFTokenMetadataEnumerableMock and directly in remix deploying on ropsten.
