### ISSUE TITLE
How to return values from a function by using deployed contract address?

### ISSUE THREAD

**Issue by lekshmikbs123** [0xcert/ethereum-erc721#128]
I have created a contract with functions...the get() is used for storing and getarray is for returning values...
```
struct arrayy{
uint256[] arrayvalue;
}
mapping(address => arrayy) arraymapping;

event logg(
uint256 z,
address sender
);

function get(uint256 y, address _owner) public{
arraymapping[_owner].arrayvalue.push(y);
emit logg(y,_owner);
}

function getarray(address _owner) internal returns(uint256[]){

return(arraymapping[_owner].arrayvalue);
}
```

Then I deployed the contract, and tried to call the get() function by using...
```
DeployedContractAddress.call(bytes4(keccak256("get(uint256,address)")),1234,0xfffff);
```
logs are not displayed. ie; when function is called by deployed address, logs are displayed. But when I tried to call function from other wallet address,its not working...Is it not possible?

Can't we return values by calling from deployed contract address...

**Comment by MoMannn** [comment]
This is not a problem with our contract so I would forward you to: [Stackoverflow](https://ethereum.stackexchange.com/) or [Reddit](https://www.reddit.com/r/ethdev/) for this type of questions.

But from what I can see getArray is internal so it can not be called from outside the contract. 
Get is public and has no restrictions to it so it can be called from any address.
