### ISSUE TITLE
Use correct global imports

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#131]
https://github.com/ethereum/remix-ide/issues/1531#issuecomment-422868250

**Comment by MoMannn** [comment]
Did you use remixd for connecting to remix? The imports work fine that way.

**Comment by fulldecent** [comment]
Works well with remixd (the newer version).

Perhaps we should explain, from scratch how a user that is used to programming with Remix IDE would get this working.

Because we use multiple repositories, our product will always be harder to use than OpenZeppelin. (Use OZ with a one-line import.) This is okay, but our documentation should be twice as good to compensate!

**Comment by fulldecent** [comment]
Closing issue, I misunderstood. Reopening the current problem as a new issue.

**Comment by fulldecent** [comment]
Reopening. I have read further on Solidity's documentation of the `import` directive. We are using `@` includes which are compatible with `remixd` and possibly other compilers/IDEs however those are proprietary extensions to Solidity.

Since this is not vanilla Solidity it is our burden to document exactly which environments this code will run in and that this is not baseline Solidity.

https://solidity.readthedocs.io/en/latest/layout-of-source-files.html?highlight=import#import

**Comment by MoMannn** [comment]
https://github.com/0xcert/ethereum-erc721/pull/154

**Comment by fulldecent** [comment]
Confirmed fixed in new branch
