### ISSUE TITLE
Fully document coding style

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#132]
Presently the coding style is consistent but undocumented.

I believe that this implementations of this contract will be running billions of dollars of commerce in the future. So every character of these contracts should be justified. That includes whitespace.

There should be no ambiguity on whether the coding style is being followed because it should be documented fully. Also include a link in CONTRIBUTING.md

Schedule: before bug bounty

---

Param might be better without a period at the end.

Source: https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format

Disclaimer: I wrote this version of the NatSpec style guide

---

Discourage (or explicitly justify!) why we use underscores everywhere. And don't cite ERC-721 as a justification, because I regret some of the decisions there!!!

**Comment by dafky2000** [comment]
It will be beneficial to encode these rules into a linter configuration as well!

https://eslint.org/ (for .js)
https://github.com/protofire/solhint (for .sol)

**Comment by fulldecent** [comment]
@dafky2000 Thank you for sharing! Do you have any examples of projects that are using this and code styles we can study?

**Comment by MoMannn** [comment]
@dafky2000 @fulldecent #171 Enforcing through solhint. Code style documentation will soon follow.

**Comment by MoMannn** [comment]
#175 Adding style guide.

**Comment by fulldecent** [comment]
Please close issues after merged.

**Comment by MoMannn** [comment]
#175
