### ISSUE TITLE
Create releases document policy for code in master

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#133]
Document merging policy for code in master.

Create a release for the current code and increment the release each time the contract code changes. (Certain changes to tests and documentation should not require a version bump.)

This includes explaining exactly what is or is not covered in the bug bounty.

---

Release policy

Git tag

Github release

npm push

---

Also note in readme

**Comment by xpepermint** [comment]
Agree! Note that changing the README also requires version change because it's an npm package and it's good to have the latest README on https://www.npmjs.com.

**Comment by xpepermint** [comment]
https://github.com/0xcert/ethereum-erc721/pull/182
