### ISSUE TITLE
Company name typo

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#135]
Company name is misspelled (styling) in the license file:

https://github.com/0xcert/ethereum-erc721/blob/master/LICENSE#L3

**Comment by MoMannn** [comment]
I don't see the misspell. Can you be more specific?

**Comment by fulldecent** [comment]
0xcert and 0Xcert

**Comment by MoMannn** [comment]
Ow yeah. To clarify this. The official company name is 0Xcert because of the rigid laws in Slovenia that state that the first letter in a companies name has to be with a capital letter. But we present ourself and use 0xcert.

**Comment by fulldecent** [comment]
Got it. I have opened an issue on the website to update on that part.

Reference: https://github.com/0xcert/ethereum-erc721/issues/135#event-1906598461
