### ISSUE TITLE
Subclassing notes

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#138]
We should more thoroughly review every `internal` function and include this in our thread model evaluation. Maybe there is a case for moving one of these to `private`. These entry points and all assumptions about them should be fully documented in `@dev` notes.

**Comment by fulldecent** [comment]
P.S. Solidity is working to change the contract inheritance model. We should also start thinking about the difference between `open` and `internal` access classes.

**Comment by MoMannn** [comment]
@fulldecent Should we schedule a call and go trough it?

**Comment by fulldecent** [comment]
Yes, please

**Comment by MoMannn** [comment]
#154
