### ISSUE TITLE
Fully document how to use ethereum-erc721 with Remix IDE

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#140]
This works well with remixd (the newer version).

Perhaps we should explain, from scratch, how a user that is used to programming with Remix IDE would get this working.

Because we use multiple repositories, our product will always be harder to use than OpenZeppelin. (Can use OZ with a one-line import.) This is okay, but our documentation should be twice as good to compensate!

**Comment by MoMannn** [comment]
@xpepermint I think we should simplify this and not use multiple repos since we will not be using the utils repo anyway.. What do you think?

**Comment by MoMannn** [comment]
https://github.com/0xcert/ethereum-erc721/pull/154

**Comment by fulldecent** [comment]
Confirmed fixed in new branch
