### ISSUE TITLE
payable

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#144]
Currently transfer functions & approve do not allow payable function implementations.

This is okay but it should be documented that this is more restrictive than the standard.

https://github.com/0xcert/ethereum-erc721/blob/master/contracts/tokens/NFToken.sol

**Comment by MoMannn** [comment]
https://github.com/0xcert/ethereum-erc721/pull/154

**Comment by fulldecent** [comment]
Confirmed fixed in latest branch

**Comment by fulldecent** [comment]
This documentation should also be updated in the interfaces.

**Comment by MoMannn** [comment]
I would add to @dev: `This function can be changed to payable.`
Since if anyones wants to make it payable he can do that by himself. I would then add to readme that this implementation does not support payable out of the box. 

@fulldecent  You ok with this?

**Comment by fulldecent** [comment]
This is good. But should also specifically say there "this implementation is more restrictive than the ERC-721 standard requires" for the avoidance of doubt.

**Comment by MoMannn** [comment]
https://github.com/0xcert/ethereum-erc721/pull/272
