### ISSUE TITLE
NFTEnumerable Issues

### ISSUE THREAD

**Issue by superphly** [0xcert/ethereum-erc721#152]
I'm trying to use both metadata and enumerable, but this is what I get. Whether I use metadata or not, this is the result i get when I try to use Enumerable.

localhost/contracts/tokens/NFTokenEnumerable.sol:105:5: TypeError: Member "removeNFToken" not found or not visible after argument-dependent lookup in contract super NFTokenEnumerable
    super.removeNFToken(_from, _tokenId);
    ^-----------------^

**Comment by MoMannn** [comment]
This is an example of how to use it:

https://github.com/0xcert/ethereum-erc721/blob/master/contracts/mocks/NFTokenMetadataEnumerableMock.sol
