### ISSUE TITLE
Use CI check to compare WET code to upstream

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#156]
Currently a few files are copy/pasted from upstream sources. It's a little WET but that's fine.

To be triple careful, we can make CI test to compare this automatically.

Here is one example of a WET test in CI: https://github.com/su-squares/ethereum-contract/blob/master/test/confirm-sol-merged.sh

Priority: LOW
Schedule: After 2.0.0 final

**Comment by MoMannn** [comment]
I would say that this is the upstream and main source and if anything it should go the otherway around. So I am closing this.
