### ISSUE TITLE
Revert messages

### ISSUE THREAD

**Issue by MoMannn** [0xcert/ethereum-erc721#170]
Should we add revert messages and if in what shape and form? We can do either by error codes or descriptions.

So for an invalid nft the error would be either:
- 400 
- Invalid nft.

Where 400 is error code representation and anyone can handle it on the front end in anyway they like. 

@xpepermint @fulldecent What are your thoughts on this?

**Comment by xpepermint** [comment]
I would leave this issue open until revert messages actually supported by nodes.

**Comment by fulldecent** [comment]
Right now this is not really usable in the real world. I recommend we consider this potentially after 2.0.0 final.

**Comment by MoMannn** [comment]
#238
