### ISSUE TITLE
Move style guide to own repo

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#178]
We can use it for other projects.

0xcert/solidity-style-guide

**Comment by xpepermint** [comment]
Now available at https://github.com/0xcert/solidity-style-guide. @MoMannn please remove it from the repo.

**Comment by fulldecent** [comment]
Blockers 

- [ ] https://github.com/0xcert/solidity-style-guide/issues/5

Then please 

- [ ] In this repo specify which version of the style guide is effective

**Comment by MoMannn** [comment]
#197

**Comment by xpepermint** [comment]
Done

**Comment by fulldecent** [comment]
The reference is not strong enough. Continuing this discussion in a separate issue at https://github.com/0xcert/ethereum-erc721/issues/202
