### ISSUE TITLE
Publish gas performance metrics

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#188]
For example, today I need to know what minting costs for each NFT flavor. But this is something we should publish in more detail.

**Comment by xpepermint** [comment]
Yup, soon :).

**Comment by fulldecent** [comment]
Hey @dafky2000 please share if you have any ideas on how we can best format and present this information.

**Comment by dafky2000** [comment]
I'm specifically interested in the differences between "v1" and "v2" so, some comparison tables would be useful in my case.

### Plain

| | ERC-721 | ERC-721 v2 |
| ------------- | ------------- | ------------- |
| transfer  | 94955 gas  | 54825 gas (-42%) |
| transferFrom  | 94955 gas  | 58655 gas (-39%) |
| mint  | 94955 gas  | 35554 gas (-63%) |
| balanceOf  | 94955 gas  | 32468 gas (-76%) |
| ownerOf  | 94955 gas  | 94955 gas (+-0%) |

### Enumerable

| | ERC-721 | ERC-721 v2 |
| ------------- | ------------- | ------------- |
| transfer  | 94955 gas  | 54825 gas (-42%) |
| transferFrom  | 94955 gas  | 58655 gas (-39%) |
| mint  | 94955 gas  | 35554 gas (-63%) |
| balanceOf  | 94955 gas  | 32468 gas (-76%) |
| ownerOf  | 94955 gas  | 94955 gas (+-0%) |

### Meta data

| | ERC-721 | ERC-721 v2 |
| ------------- | ------------- | ------------- |
| transfer  | 94955 gas  | 54825 gas (-42%) |
| transferFrom  | 94955 gas  | 58655 gas (-39%) |
| mint  | 94955 gas  | 35554 gas (-63%) |
| balanceOf  | 94955 gas  | 32468 gas (-76%) |
| ownerOf  | 94955 gas  | 94955 gas (+-0%) |

**Comment by MoMannn** [comment]
Closing this for now. We will publish main results in the readme after automated tests and final release of v2.
