### ISSUE TITLE
README structure - meta and enum descriptions wrong way round

### ISSUE THREAD

**Issue by rossbulat** [0xcert/ethereum-erc721#193]
The descriptions of the metadata and enumerable tokens should be switched in README Structure section. Please update.

> **nf-token-metadata.sol:** This implements optional ERC-721 support for enumeration. It is useful if you want to know the total supply of tokens, to query a token by index, etc.

> **nf-token-enumerable.sol:** This implements optional ERC-721 metadata features for the token contract. It implements a token name, a symbol and a distinct URI pointing to a publicly exposed ERC-721 JSON metadata file.

**Comment by MoMannn** [comment]
#194
