### ISSUE TITLE
Undocumented implementation detail in _burn

### ISSUE THREAD

**Issue by codyborn** [0xcert/ethereum-erc721#198]
In the current implementation, the minter can resurrect a burned NFT.  This might be unexpected behavior for some, so mentioning this behavior in the _notice_ section for __burn_ would be helpful.

**Comment by MoMannn** [comment]
#208
 @PhABC @codyborn Will this be sufficient?

**Comment by fulldecent** [comment]
Ping @codyborn @PhABC

**Comment by PhABC** [comment]
I think that should be enough. Projects might want to "revive" tokens and nothing about the standard states that burning should be permanent.
