### ISSUE TITLE
Possible reminting of tokens

### ISSUE THREAD

**Issue by PhABC** [0xcert/ethereum-erc721#203]
It is currently possible to re-mint a token that was burnt.

The `_mint()` fucntion only verifies that `require(idToOwner[_tokenId] == address(0))`, which will return true for `_tokenId` that was burnt previously.

Possible fix is to set the "burn" address to `0xdead` instead of `0x0`.

I understand the burning method is not in the specificarion, but wanted to share it case it was of interest to the developers.

**Comment by MoMannn** [comment]
Duplicate of #198.
