### ISSUE TITLE
Consider the case when token is mistakenly transferred to NFToken contract address

### ISSUE THREAD

**Issue by gundas** [0xcert/ethereum-erc721#204]
Hello,

A lot of ERC-20 tokens has been lost (locked) by accidentally transferring them to the Token Contract address itself (e.g. all BNB tokens belonging to [BNB Token Contract](https://etherscan.io/address/0xB8c77482e45F1F44dE1745F52C74426C631bDD52) are lost, and it is just one of  many examples).

I would suggest that NFToken  ERC-721 reference implementation should forbid transferring tokens ```_to``` the ```address(self)```  in the protected ```_transfer``` function. In this case, default implementation would prevent people from making the mistake and if this functionality is required by some ERC-721 contract the function could be overridden.

There is also an alternative solution (used a lot in newer ERC-20 tokens): 
 - a function which would allow the owner to transfer-out  (any?) Tokens belonging to the ERC-721 Token Contract address. It could be added to Mock implementations (probably defined in separate base contract).

The main idea is to have something in the reference implementation, so developers do not forget about this case, like it had happened with many ERC-20 tokens.

**Comment by MoMannn** [comment]
ERC721 has by design a method to prevent such problems called `safeTransferFrom` which checks if receiving address is capable of receiving the token and fails otherwise. This is the primary function that should be used for transferring tokens. 

Is this a sufficient answer?

**Comment by gundas** [comment]
Yes, thank you for the explanation. 
I overlooked the difference between the ```safeTransferFrom``` and  ```transferFrom```.
