### ISSUE TITLE
Example code should not allow destroy

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#218]
Copied from https://github.com/0xcert/framework/issues/385

---

The baseline nf-token-mock in the contracts directory includes a owner-usable destroy function. This makes the contract centralized by default. (Since owner can destroy, create and transfer to somebody else.)

The example contract should remove this function or the file name and contract name should be updated to show that the recommended baseline feature set.

Separately, /testing/ mocks are okay to have this additional features because they are for testing and not general use.

**Comment by MoMannn** [comment]
#217
