### ISSUE TITLE
Ensure Remix instructions work in the new Remix

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#226]
We have instructions to show how to test this package using Remix.

Remix is changing. Source: https://remix.readthedocs.io/en/latest/layout.html

Let's confirm the instructions remain valid with the updated version.

**Comment by MoMannn** [comment]
Everything works the same. But you do need to enable compiler and deploy plugins but I do not think that this should be a part of the tutorial.

**Comment by fulldecent** [comment]
Confirming the instruction works on the new Remix.
