### ISSUE TITLE
isContract is incorrect

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#228]
Technically, the documentation at https://github.com/0xcert/ethereum-erc721/blob/master/src/contracts/utils/address-utils.sol is incorrect. Specifically, a contract that is constructing will return `0` until it is completing construction.

This does not affect us much, but somebody using just that code will get unexpected results, so this is a security issue.

References:

* https://www.reddit.com/r/ethereum/comments/916xni/how_to_pwn_fomo3d_a_beginners_guide/
* https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Address.sol

**Comment by MoMannn** [comment]
#229
