### ISSUE TITLE
Consider refactoring code to monoliths (no overriding) like in 0xcert framework.

### ISSUE THREAD

**Issue by MoMannn** [0xcert/ethereum-erc721#237]
https://github.com/0xcert/framework/tree/master/packages/0xcert-ethereum-erc721-contracts/src/contracts

**Comment by xpepermint** [comment]
Is this still the issue in the latest version of solidity?

**Comment by MoMannn** [comment]
Yes, but I think that for this we need to prioritise contracts being readable. So I am closing this.
