### ISSUE TITLE
Add selling points

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#24]
Every GitHub project needs selling points

* Complete implementation (all functions implemented)
* XX% code coverage Truffle testing
* It is subclassable so you can add your own features while relying on our base work
* The code is verified by the community and has an active bug bounty

**Comment by fulldecent** [comment]
What additional features are added (minting, burning)?

**Comment by xpepermint** [comment]
https://github.com/0xcert/ethereum-erc721/pull/35
