### ISSUE TITLE
nf-token.sol: APPROWED => APPROVED typo

### ISSUE THREAD

**Issue by sam-at-luther** [0xcert/ethereum-erc721#242]
APPROWED is used several places in nf-token.sol. I assume this is a typo and should be renamed to APPROVED?

**Comment by MoMannn** [comment]
#247

**Comment by xpepermint** [comment]
@sam-at-luther we noticed that your contribution is eligible to receive a T-shirt. Please send an email with your details (size, name, address) to `bounty@0xcert.com`.
