### ISSUE TITLE
Add screenshot

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#25]
Let's find a way to add a screenshot.

- Maybe deploy a token (to mainnet) and load it up on Toshi. Add a screenshot of Toshi.
- Maybe deploy a contract and show the read contract page on etherscan like https://etherscan.io/address/0x6731560e455537c9f088ea02a47a0ecfa28a9231#readContract
- Maybe a flow diagram, anything

**Comment by xpepermint** [comment]
https://github.com/0xcert/ethereum-erc721/pull/35
