### ISSUE TITLE
Add bug bounty

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#26]
Add link to bug bounty

**Comment by xpepermint** [comment]
Waiting for https://github.com/ethereum/EIPs/pull/1072#issuecomment-387739114 to be resolved.

**Comment by fulldecent** [comment]
Change approved: https://github.com/ethereum/EIPs/pull/1072#pullrequestreview-120490287

**Comment by xpepermint** [comment]
https://github.com/0xcert/ethereum-erc721/issues/46
