### ISSUE TITLE
Created NFT has no creator

### ISSUE THREAD

**Issue by 0x00xx** [0xcert/ethereum-erc721#268]
Hi,

I just created my first test NFT according to this tutorial: https://www.quicknode.com/guides/solidity/how-to-create-and-deploy-an-erc-721-nft

But somehow the created NFT has no creator (but I should be the owner ofc)

Is there a problem in the library?

**Comment by MoMannn** [comment]
You will need to provide much more information. 
On which network did you deploy? What is the contract address? What NFT ID did you create? How did you check the owner?

**Comment by 0x00xx** [comment]
Sorry for the missing information. I have deployed it on the Rinkeby testnet.
Here is the contract code:
```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.6;
 
import "./tokens/nf-token-metadata.sol";
import "./ownership/ownable.sol";
 
contract Bla is NFTokenMetadata, Ownable {
 
  constructor() {
    nftName = "Synth NFT";
    nftSymbol = "SYN";
  }
 
  function mint() external onlyOwner {
    super._mint(msg.sender, 1);
    super._setTokenUri(1, "https://ipfs.io/ipfs/QmaH1buwvzi5awRtEv7pTRwLArXs6BjNUkPqAmbK5dgJKJ");
  }
 
}
```

The contract ist deployed at: https://rinkeby.etherscan.io/address/0xa7A66Ed691EBEB017f288660b3099e103Af97f67

The creator is checked with Opensea: https://testnets.opensea.io/assets/0xa7a66ed691ebeb017f288660b3099e103af97f67/1
![image](https://user-images.githubusercontent.com/21081469/129700080-715473cf-415a-468f-bf01-3075cd01f945.png)


Normally above the description is the creator. Weirdly enough the same code showed the creator about 7-10 days ago.

**Comment by MoMannn** [comment]
In this case this has nothing to do with the code. The NFT contract is created and NFT was minted correctly. 

You will need to contact OpenSea as to why it is not registering you as the creator. 

I would suggest contacting them on discord: https://discord.com/invite/opensea

**Comment by 0x00xx** [comment]
K, thx for the confirmation.

Will try to contact them!
