### ISSUE TITLE
Metadata extension is not compliant

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#27]
Currently metadata is not compliant with the standard. Standard is pure, implementation is view.

Will consider to change the standard because everyone is doing this. But for now this should be noted.

**Comment by fulldecent** [comment]
More discussion here https://github.com/ethereum/EIPs/pull/1072#issuecomment-387739114

**Comment by xpepermint** [comment]
Alright, we leave it as it is then.

**Comment by xpepermint** [comment]
Resolved with https://github.com/ethereum/EIPs/pull/1072
