### ISSUE TITLE
Not an issue just need some advice!

### ISSUE THREAD

**Issue by erectilereptiles** [0xcert/ethereum-erc721#273]
Sorry i am new to github i hope this doesnt affect your profile in any way! I am a student and my project team is using your code for our project. We needed to tokenise financial assets, but were allowed to get a token instead of building our own from scratch. It has been absolutely excellent using your token code! Everything is perfect but now for the last iteration of our project we said we would be able to delete tokens. I noticed you have an internal burn function and the comment says it needs to be implemented from an external burn function that is user created. I tried to implement one with the external mint function as a reference and came up with this:

function burn (uint256 _tokenId) external onlyOwner {
      super._burn(_tokenId);
  }

Is this incorrect? It is not allowing me to delete a token once it is minted. Could you help us with what we are doing wrong?

Thanks so much in advanced!

**Comment by MoMannn** [comment]
Your code looks ok but the `onlyOwner ` part means only the contract creator has the ability to burn. So only the contract creator can send this transaction.

**Comment by erectilereptiles** [comment]
Hi thank you! I am the contract owner, but also i did try it without the onlyOnwer and it still did not work!

**Comment by MoMannn** [comment]
Cam you give a link to the contract, the transaction you are making (you should get an error message that tells you what is wrong)

**Comment by erectilereptiles** [comment]
Sorry im not extremely competent in these things as i am still a student! When clicking on the transaction error this is the etherscan page it takes me to:
https://ropsten.etherscan.io/tx/0xc167b931eb62dda3cdb1ce1f7d2fcd4d9f562af399d03098802dfbd57901ba94
Its on a test network so im unsure of whether you can see it. Please let me know if i need to send screenshots!

**Comment by erectilereptiles** [comment]
This is the smart contract address:
0x0A5A3BFa844afa7bD4baC5B5EBf8C96c7719d48e

**Comment by MoMannn** [comment]
Hum. Can you post your full code?

**Comment by erectilereptiles** [comment]
No problem! I added some stuff as the token needs to represent a personal loan. Please let me know if that is the problem

// SPDX-License-Identifier: MIT
pragma solidity 0.8.6;
 
import "https://github.com/0xcert/ethereum-erc721/src/contracts/tokens/nf-token-metadata.sol";
import "https://github.com/0xcert/ethereum-erc721/src/contracts/ownership/ownable.sol";
 
contract newNFT is NFTokenMetadata, Ownable {
    uint256 loanamount;
        uint256 interestrate;
        uint256 termmonths;
    
  constructor() {
    
    nftName = "Deloitte NFT";
    nftSymbol = "DTN";
        
  }
  function mint(address _to, uint256 _tokenId, string calldata _uri, uint256 amount, uint256 rate,uint256 term) external onlyOwner {
    super._mint(_to, _tokenId);
    super._setTokenUri(_tokenId, _uri);
    tokenidToloanamount[_tokenId] = amount;
    tokenidTointerestrate[_tokenId] = rate;
    tokenidTotermmonths[_tokenId] = term;
  }
  
  function burn (uint256 _tokenId) external onlyOwner {
      super._burn(_tokenId);
  }
  
  
  function getLoanAmount (uint256 _tokenId) public view returns (uint256 amount) {
      amount = tokenidToloanamount[_tokenId];
      return amount;
  }
  
  function getRate (uint256 _tokenId) public view returns (uint256 rate) {
      rate = tokenidTointerestrate[_tokenId];
      return rate;
  }
  
  function getTerm (uint256 _tokenId) public view returns (uint256 term) {
      term = tokenidTotermmonths[_tokenId];
      return term;
  }
   mapping (uint256 => uint256) public tokenidToloanamount;
   mapping (uint256 => uint256) public tokenidTointerestrate;
   mapping (uint256 => uint256) public tokenidTotermmonths;
 
}

**Comment by MoMannn** [comment]
Your code works ok for me. Did you deploy the contract again after adding the burn functionality? Once the code is deployed it cannot be changed. So if you add functionality you need to redeploy it.

Also I would suggest adding:

```
delete tokenidToloanamount[_tokenId];
delete tokenidTointerestrate[_tokenId];
delete tokenidTotermmonths[_tokenId];
```

To the burn function.
