### ISSUE TITLE
Update and refactor tests

### ISSUE THREAD

**Issue by lknix** [0xcert/ethereum-erc721#32]
Tests should be testing a single unit (function). Currently we don't test all functions directly since some of them are tested through other functions. This doesn't follow the best practices because it's misleading when tests start to fail and it leaves out edge cases. Ideally, tests should:
1. Every test should test a single unit. 
1. Every test should set up the required contract state directly prior to testing.
1. Every unit should be fully covered.

**Comment by xpepermint** [comment]
4. Refactor variables from `var` to `let`/`const`.

**Comment by xpepermint** [comment]
Closing for now. Feel free to reopen it if needed.
