### ISSUE TITLE
Deploy main net

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#38]
Just for fun, could you please:

* Take the example at https://github.com/lknix/ethereum-erc721/blob/4cc409a6ddfc1183bbe0fdd82a8dfff07222f24e/README.md
* Remove `onlyOwner`
* Deploy to main net and ropsten
* Publish code on etherscan.io

Then you can add to the README:

> We deployed a contract you can play with RIGHT NOW. No need to install software. In this test version of the contract, anybody can mint or burn tokens, so don't use it for anything important.
>
> Mainnet address: xxxxx
> Ropsten address: xxxxx

**Comment by xpepermint** [comment]
https://github.com/0xcert/ethereum-erc721/pull/44
