### ISSUE TITLE
Token naming suggestions

### ISSUE THREAD

**Issue by lknix** [0xcert/ethereum-erc721#4]
How about if we change current naming that:
1. `ERC721.sol` (interface) -> `ERC721Interface.sol` or `ERC721Standard.sol` and `ERC721implementation.sol` -> `ERC721.sol`;
2. Alternatively we move interfaces in `tokens/interfaces` and name both `ERC721.sol` (interface and implementation).

If the plan is that our implementation gets reused then we need to have simpler names. `ERC721implementation` is way too long and verbose. Thoughts?

**Comment by xpepermint** [comment]
Interfaces could be prefixed by the `I` but it's strange when you have names like `ERC721.sol`.

**Comment by xpepermint** [comment]
```
/tokens/ERC721.sol (interface)
/tokens/NFToken.sol 
```
