### ISSUE TITLE
Send people to a non-scammy Ropsten faucet

### ISSUE THREAD

**Issue by bmann** [0xcert/ethereum-erc721#58]
For manager.0xcert.org, the suggested website for getting Ropsten ether is http://ethereumfaucet.info/ is filled with ads and looks super scammy.

Instead, use the Metamask faucet https://faucet.metamask.io/ or ALabs Faucet http://faucet.ropsten.be:3001/

@lknix [asked me to file an issue](https://twitter.com/lukakacil/status/998489512102825984) but it wasn't clear what repo to put this in. Please point me at the manager repo -- I have other bugs to file :)

**Comment by xpepermint** [comment]
It was I who googled for "eth faucet" and took the first link on the list :). Thanks @bmann for pointing that out. It's fixed.
