### ISSUE TITLE
ERC721 Enumerable: purpose of idToIndex?

### ISSUE THREAD

**Issue by lknix** [0xcert/ethereum-erc721#6]
We set it in `_mint` function and don't use it anywhere.

```
contracts/tokens/ERC721EnumerableImplementation.sol:  mapping(uint256 => uint256) internal idToIndex;
contracts/tokens/ERC721EnumerableImplementation.sol:    idToIndex[_id] = tokens.length;
```

**Comment by MoMannn** [comment]
It was added for the purpose of a burn function. I decided that burn function is not needed for a basic implementation but then forgot to remove the mapping.

**Comment by lknix** [comment]
I have removed it in my code review branch. Will open a PR soon for a review.

**Comment by MoMannn** [comment]
#13
