### ISSUE TITLE
ERC721 Enumerable: missing tests

### ISSUE THREAD

**Issue by lknix** [0xcert/ethereum-erc721#7]
1. missing tests for function `_mint`
1. missing tests for function `removeNFToken`
1. missing tests for function `addNFToken`

**Comment by MoMannn** [comment]
This points all get tested by other tests.. So when testing totalSupply and tokenByIndex you test mint. When testing tokenOfOwnerByIndex you test addNFToken and when testing burn you test removeNFToken..

**Comment by lknix** [comment]
Yes, true, but tests should be testing single units by design. You don't want your test about sending tokens to fail because there's a new bug in `_mint` function. First it's not clear from the tests report what the problem is, which hinders development and maintenance. Second you usually don't provide full test coverage by doing this.

**Comment by MoMannn** [comment]
We can add a specific test for mint but addNFToken and removeNFToken are only helper function for transfering/minting/burning.. So you cannot test them expect by testing transfering/minting/burning..

**Comment by MoMannn** [comment]
#16
