### ISSUE TITLE
ERC721 Metadata: naming conflicts

### ISSUE THREAD

**Issue by lknix** [0xcert/ethereum-erc721#8]
We should rename `issuerName`, `issuerSymbol` which are too restrictive and specific for our use case.

**Comment by MoMannn** [comment]
In what way are they restrictive? The contract will always be the issuer of new tokens...

**Comment by MoMannn** [comment]
Ok, we can rename it to nftName and nftSymbol.

**Comment by MoMannn** [comment]
#16
