### ISSUE TITLE
Approval() emit logic is not entirely defined in spec

### ISSUE THREAD

**Issue by shrugs** [0xcert/ethereum-erc721#85]
Via a chat on ETH-NFT/Lobby, we've determined that the `Approval()` even should be emitted on both sets OR reaffirmations. 

https://github.com/ethereum/EIPs/pull/1151

(this is not a bug report, as previous behavior was undefined)

**Comment by shrugs** [comment]
ah, I see this was preemptively fixed in https://github.com/0xcert/ethereum-erc721/commit/1f4b5b65ce43fde7cb2f51e4eb4e3cf2aa1c1b56#diff-9d1e91260b287bdd6c54cb0a7a40678b

**Comment by xpepermint** [comment]
Thanks for your effort anyway @shrugs.
