### ISSUE TITLE
ERC 721: canTransfer should modify _transfer function

### ISSUE THREAD

**Issue by lknix** [0xcert/ethereum-erc721#9]
I think `canTransfer` modifier should be moved to private `_transfer` function instead of other wrapping functions. If somebody decides to build upon our implementation then decoupling these could pose a serious risk: one just needs to add another function which calls `_transfer` and forget to add the modifier. Or changes _transfer to external.

**Comment by MoMannn** [comment]
_transfer is a private function so it cannot be overridden or called if a contracts inherits from NFToken contract... If anyone is modifying NFToken as it is he can change anything anyway..

**Comment by lknix** [comment]
Here is my reasoning and possible bug scenarios (all of them dealing with user doing something wrong):
1. User inherits and overrides `safeTransferFrom` w/o adding modifiers -> open acess.
1. User inherits and adds its own `specialTransfer` which uses `_transfer`. Here he has to explicitly check for state change permissions which happen in `_transfer`. If he fails to do it, then we have open access again.
1. User modifies our existing implementation and does some stupid things like changing _transfer to external or other weird things.

I'm not saying this would "guard" against all stupidity but I think it's a good design if you keep permission checks coupled with the code that does states changes. Wdyt? I don't see any drawbacks but potentially we shrink surface for introducing some bugs.

**Comment by lknix** [comment]
You're right. Just checked the docs and private functions aren't visible to derived contracts - my bad. OK, this invalidates the 1 and 2 which were the most significant ones. Closing this issue.
