### ISSUE TITLE
5300 Gas Cost for Unnecessary State Change

### ISSUE THREAD

**Issue by mudgen** [0xcert/ethereum-erc721#91]
In the removeNFToken function in the NFTokenEnumerable.sol file `ownerToIds[_from][lastTokenIndex]` is set to 0 twice instead of once. This is redundant and costs about 5300 extra gas.

Here is the code I am talking about:

```
 ownerToIds[_from][lastTokenIndex] = 0;
 
 ownerToIds[_from].length--;
```
The first line obviously sets `ownerToIds[_from][lastTokenIndex]` to 0.  Reducing the length of the array also sets `ownerToIds[_from][lastTokenIndex]` to 0.  

So it makes sense to get rid of this line: ownerToIds[_from][lastTokenIndex] = 0;.

**Comment by MoMannn** [comment]
You are correct. The compiler automatically cleans up unoccupied slots when array length is decreased. #93

**Comment by mudgen** [comment]
This was fixed/improved. Great this was done so quickly.
