### ISSUE TITLE
ERC721 implementation shouldn't extend from Ownable

### ISSUE THREAD

**Issue by mg6maciej** [0xcert/ethereum-erc721#97]
I have to say it IS convenient in my unit tests, that it does, but not all deployments will require it.

**Comment by MoMannn** [comment]
You are correct, we will move the Ownable to the mocks.

**Comment by MoMannn** [comment]
#98 @mg6maciej How does this look to you now? The implementation itself is without ownable but mocks have it.

**Comment by mg6maciej** [comment]
@MoMannn LGTM. If possible I would go with a bit different inheritance to avoid duplicating `mint` and `burn` in 4 mock contracts. Something like `NFTokenEnumerableMock is NFTokenEnumerable, NFTokenMock`.

**Comment by MoMannn** [comment]
@mg6maciej Ok, then I will close this issue. We will consider your suggestion about inheritance but that is a separate thing so I will open another issue for discussion about it.
