### ISSUE TITLE
Different inheritance to avoid duplicating mint and burn functions in mock contacts.

### ISSUE THREAD

**Issue by MoMannn** [0xcert/ethereum-erc721#99]
As per @mg6maciej suggestion: 

If possible I would go with a bit different inheritance to avoid duplicating mint and burn in 4 mock contracts. Something like NFTokenEnumerableMock is NFTokenEnumerable, NFTokenMock.

I am opening an issue about this.

@xpepermint 
@lknix

**Comment by xpepermint** [comment]
Hum, not sure ... these are mocks ... let me think about that ...

**Comment by MoMannn** [comment]
Well my thinking is that this mocks are made so that anyone who wants to develop on top can just take the appropriate mock and start working on it. Inheritance is not as important as simplicity and clarity in this case and I think making mocks inherit from one another will add complexity where there is no need.

**Comment by xpepermint** [comment]
I agree with @MoMannn. Mocks are just code examples. Thanks for the proposal @mg6maciej but we think mocks should be as clean/clear as possible - the repeat your self piece of code if you wish.

If you think that we misunderstood your proposal, feel free to reopen it.
